---
apiVersion: hello.stackable.tech/v1alpha1
kind: HelloCluster
metadata:
  name: hello-world
spec:
  image:
    custom: oci.stackable.tech/sdp/hello-world:0.0.1-SNAPSHOT-stackable0.0.0-dev
    productVersion: 0.0.1
  recipient: "Stackable"
  color: "blue"
  clusterConfig:
    listenerClass: external-unstable
  servers:
    roleGroups:
      default:
        replicas: 1
