---
apiVersion: hello.stackable.tech/v1alpha1
kind: HelloCluster
metadata:
  name: hello-world
spec:
  image:
    custom: docker.stackable.tech/stackable/hello-world:0.0.1-SNAPSHOT-stackable0.0.0-dev
    productVersion: 0.0.1
  recipient: "Stackable"
  color: "blue"
  clusterConfig:
    listenerClass: external-unstable
    vectorAggregatorConfigMapName: vector-aggregator-discovery
  servers:
    config:
      logging:
        enableVectorAgent: true
        containers:
          hello:
            console:
              level: INFO
            file:
              level: INFO
            loggers:
              ROOT:
                level: INFO
    roleGroups:
      default:
        replicas: 1